### ISSUE TITLE
Timing Source Inconsistencies in Primary Configuration

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/StandardEngine#56]
A "Timing Source Type" change results in a unit scaling (conversion) in the Timing Source dt numeric control, and the units are undocumented. Options: 1) Create a "units" string indicator with no visible label next to the Timing Source dt control and refresh it with each change of Timing Source Type, or 2) Refresh the caption of Timing Source dt with each change of Timing Source Type to include units (example: "Timing Source dt (msec)").

**Comment by smithed** [comment]
I disagree. The unit is always the same. "Clock ticks" is the unit :)
I do think it might make sense to change from "dt" to "ticks" to make it clear the value you enter is *not* a function of time, its a function of the clock source (which might be a function of time, but is not required to be).

In any case, please don't do (1) since lv units are annoying to use.

**Comment by Beazurt** [comment]
I agree, clock ticks are the unit and are technically correct. This has been a common point of confusion though, so we can fix with a better caption and documentation.

**Comment by Beazurt** [comment]
Added a tip strip. It might not be perfect, but it should be more clear than before. ad34b9f
