### ISSUE TITLE
Read Buffered Error - No Reset Method

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/StandardEngine#82]
Following up on https://github.com/LabVIEW-DCAF/ExecutionInterface/issues/33. The actual implementation of the reset is in the Standard Engine.

**Comment by jacobson3** [comment]
@becega Because of the update made to the Execution Interface repo to change the connector pane of the Read Buffered Error VI, the Standard Engine's Read Buffered Error has a connector pane mismatch. This is causing the project templates to load broken.

https://github.com/LabVIEW-DCAF/ExecutionInterface/commit/436c7d61d5aa56dd883f60f54c174060844678dc
